yeogiprj/urls.py
from venv import create
from django.conf import settings
from django.contrib import admin
from django.urls import path
import account.views
from yeogiapp import views
from django.conf.urls.static import static

urlpatterns = [
    path('create_recomment/<int:post_id>/<int:comment_id>',views.create_recomment, name="create_recomment"),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('postdelete/<int:post_id>', views.postdelete, name='postdelete'),
    path('postdetail/<int:post_id>', views.postdetail, name='postdetail'),
    path('postlike/<int:post_id>', views.postlike, name='postlike'),
    path('postupdate/<int:post_id>', views.postupdate, name='postupdate'),

    path('commentcreate/<int:post_id>', views.commentcreate, name='commentcreate'),
    path('commentdelete/<int:comment_id>', views.commentdelete, name='commentdelete'),
    path('commentupdate/<int:comment_id>', views.commentupdate, name='commentupdate'),

    path('account/login', account.views.login_view, name="login"),
    path('account/logout', account.views.logout_view, name="logout"),
    path('account/signup', account.views.signup_view, name='signup'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

yeogiapp/models.py
# from turtle import update
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    #사용자
    user = models.ForeignKey(User, on_delete=models.CASCADE, default = '')
    #좋아하는 사용자
    like_users = models.ManyToManyField(User, related_name='like_posts')
    #제목
    title = models.CharField(max_length=200)
    #본문
    body = models.TextField()
    #날짜
    date = models.DateTimeField(auto_now_add=True)
    #공간사진
    spacePhoto = models.ImageField(blank=True, null=True, upload_to='space_photo')
    #좋아요수
    likeNum = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Comment(models.Model):
    #사용자
    user = models.ForeignKey(User, on_delete=models.CASCADE, default = '')
    #게시글
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    #댓글 내용
    comment = models.TextField()
    #날짜
    date = models.DateTimeField(auto_now_add=True)
    # parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.comment

class ReComment(models.Model):
    recomment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    body = models.CharField('대댓글', max_length=150)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body 

yeogiapp/forms.py
from django import forms
from .models import Post, Comment, ReComment

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'spacePhoto']

    def __init__(self, *args, **kwargs):
        super(PostModelForm, self).__init__(*args, **kwargs)
        
        self.fields['title'].widget.attrs = {
            'class' : 'form-control',
            'placeholder' : "게시글 제목을 입력해주세요",
            'rows':20
        }

        self.fields['body'].widget.attrs = {
            'class' : 'form-control',
            'placeholder' : "게시글 본문을 입력해주세요",
            'rows':20
        }

        self.fields['spacePhoto'].widget.attrs = {
            'class' : 'form-control'
        }

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']  

    def __init__(self, *args, **kwargs):
        super(CommentModelForm, self).__init__(*args, **kwargs)
        
        self.fields['comment'].widget.attrs = {
            'class' : 'form-control',
            'placeholder' : "댓글을 입력해주세요",
            'rows': 5
        }
 
        fields = ['comment']

class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        fields = ['body']  

        

yeogiapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import is_valid_path
from .models import Post, Comment
from .forms import PostModelForm, CommentModelForm, ReCommentForm
from django.core.paginator import Paginator
from django.db.models import Count

# Create your views here.
def home(request):
    #posts = Post.objects.all()
    posts = Post.objects.filter().order_by('-date')
    #paginator = Paginator(posts, 5)
    #pagnum = request.GET.get('page')
    #posts = paginator.get_page(pagnum)

    return render(request, 'index.html', {'posts':posts})

def postcreate(request):
    #request method가 POST일 경우 : 입력값 저장
    if request.method == 'POST' or request.method=='FILES':
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.user = request.user
            form.save()
            return redirect('home')
    #request method가 GET일 경우 : form 입력 html 띄우기
    else:
        form = PostModelForm()
    return render(request, 'post_form.html', {'form':form})

def postdelete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('home')

def postupdate(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if (request.method == 'POST' or request.method == 'FILES'):
        form = PostModelForm(request.POST, request.FILES, instance=post)
        if (form.is_valid()):
            form.save()
        return redirect('home')

    else:
        form = PostModelForm(instance=post)
        return render(request, 'post_update.html', {'form' : form, 'post_detail' : post})

def postdetail(request, post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    comment_form = CommentModelForm()
    recomment_form = ReCommentForm()
    return render(request, 'post_detail.html', {'post_detail':post_detail, 'comment_form':comment_form,
    'post_id':post_id, 'recomment_form':recomment_form,})

def postlike(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)
        if post.like_users.filter(pk=request.user.pk).exists():
            post.like_users.remove(request.user)
            usercount = post.like_users.all().count()
            post.likeNum = usercount
            post.save()
        else:
            post.like_users.add(request.user)
            usercount = post.like_users.all().count()
            post.likeNum = usercount
            post.save()
        return redirect('postdetail', post_id)
    return redirect('login')

def commentcreate(request, post_id):
    filled_form = CommentModelForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(Post, pk=post_id)
        finished_form.user = request.user
        finished_form.save()
    return redirect('postdetail', post_id)

def commentdelete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = get_object_or_404(Post, pk=comment.post.id)
    comment.delete()
    return redirect('postdetail', post.id)

def commentupdate(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = get_object_or_404(Post, pk=comment.post.id)
    if (request.method == 'POST'):
        form = CommentModelForm(request.POST, instance=comment)
        if (form.is_valid()):
            form.save()    
        return redirect('postdetail', post.id)
    else:
        form = CommentModelForm(instance=comment)
        return render(request, 'comment_update.html', {'post_detail' : post, 'comment_detail' : comment, 'form' : form})


def create_recomment(requset, post_id, comment_id):
    filled_form = ReCommentForm(requset.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        # finished_form.recomment = get_object_or_404(Post, pk=post_id)
        finished_form.recomment = get_object_or_404(Comment, pk=comment_id)
        finished_form.save()
    return redirect('postdetail', post_id)

yeogiapp/templates/comment_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="text-bg-dark p-3"><h3>댓글 수정</h3></div>
        <form action="{% url 'commentupdate' comment_detail.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form }}
            <span class="text-start" style="float: left;"><a class="btn btn-outline-dark mt-auto" href="{% url 'home' %}">목록으로</a></span>
            <span class="text-center" style="float: right;"><input class="btn btn-outline-dark mt-auto" type="submit" value="수정하기"></span>
        </form>
    </div>
</body>
</html>

yeogiapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<body>
    {% if user.is_authenticated %}
    <a class="btn btn-outline-dark mt-auto" href="{% url 'postcreate' %}">게시물 추가</a><br>
    {% endif %}
    <br><br><br>
    <hr>
    {% for post in posts %}
        <a href="{% url 'postdetail' post.id %}">
            {{ post.title }}
        </a>
        <hr>
    {% endfor %}

    <br><br><br>
    {% if user.is_authenticated %}
    <a class="dropdown-item" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
        Logout
    </a>
    {% else %}
        <a href="{% url 'login' %}">로그인버튼</a>
    {% endif %}
</body>

yeogiapp/templates/map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Map</title>
</head>
<body>
</body>
</html>

yeogiapp/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script>
      function postdelete() {
          if (confirm("정말로 삭제하시겠습니까?"))
              location.href="{% url 'postdelete' post_detail.id %}";
      }
  </script>
  <style>
    * {
      color:black;
    }
  </style>
</head>
<body>
  <div class="container">
    {{ post_detail.title }}
    {{ post_detail.body }}
    {{ post_detail.date }}
    {% if post_detail.spacePhoto %}         
        <img src="{{ post_detail.spacePhoto.url }}"> <br><br><br>
    {% else %}
        <img src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" width="450px" height="300px" alt="..." /><br><br><br>
    {% endif %}

    {% if user == post_detail.user %}
    <span class="text-center" style="float: right;"><a class="btn btn-outline-dark mt-auto" href="{% url 'postupdate' post_detail.id %}">수정</a></span>
    <span class="text-center" style="float: right;"><a class="btn btn-outline-dark mt-auto" onclick="postdelete()">삭제</a></span>
    {% endif %}
    <div>
        <form action="{% url 'postlike' post_detail.id %}" method='POST'>
          {% csrf_token %}
          {% if user in post_detail.like_users.all %}
            <input type="submit" value='좋아요 취소'>
          {% else %}
            <input type="submit" value='좋아요'>
          {% endif %}
        </form>
    </div>
    좋아요 개수 : {{ post_detail.likeNum }}

    <br><br><br>
    {% for comment in post_detail.comment_set.all %}
    <span class="badge rounded-pill bg-light">{{ comment.date}}</span>    
    {{ comment }}
    {% if user == comment.user %}
    <a href="{% url 'commentupdate' comment.id %}"><span class="badge rounded-pill bg-black" style="float: right;">수정</span></a>
    <a href="{% url 'commentdelete' comment.id %}"><span class="badge rounded-pill bg-black" style="float: right;">삭제</span></a>
    {% endif %}
    <hr>
    {%for recom in comment.recomment_set.all%}
    &nbsp;&nbsp;🐾{{ user.username }}:{{recom}} {{ comment.date }}<br>
    {% endfor %}
    <form method="post" action="{% url 'create_recomment' post_id comment.id %}">
      {%csrf_token%}
      <!-- {% for recom_form in recomment_form %}
          {%if recom_form.label != 'Comment' %}
          {{recom_form.label}} : {{recom_form}}
          {%endif%}
      {%endfor%} -->
      {{ recomment_form }}
      <input type="hidden" name="comment" value={{comment.id}}>
      <input type="submit">
  </form>
<hr>
    {% endfor %}

    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'commentcreate' post_detail.id  %}">
        {% csrf_token %}
        <div class="form-group">
            {{ comment_form }}
        </div>
        <input type="submit" class="btn btn-warning btn-icon-split btn-sm" value="댓글 입력">
    </form>
    {% endif %}
  </div>
</body>
</html>

yeogiapp/templates/post_form.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-striped">
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-dark" style="float:right;">게시물 등록</button>
</form>

yeogiapp/templates/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="text-bg-dark p-3"><h3>게시글 정보 수정</h3></div>
        <form action="{% url 'postupdate' post_detail.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form }}
            <span class="text-start" style="float: left;"><a class="btn btn-outline-dark mt-auto" href="{% url 'home' %}">목록으로</a></span>
            <span class="text-center" style="float: right;"><input class="btn btn-outline-dark mt-auto" type="submit" value="수정하기"></span>
        </form>
    </div>
</body>
</html>

yeogiapp/templates/review.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Review</title>
    <link rel="stylesheet" href="{%static './css/review.css' %}">
</head>
<body>
    <div class="review" style="border: solid 4px #FFC700;">
        <div class="review-top">
            <div class="writer-profile">
                <img src="{%static './image/user.png' %}">
            </div>
            <div class="review-user">
                <div class="review-user-id">userID</div>
                <div class="review-date">20XX.XX.XX</div>
            </div>
            <button class="review-bin-button" type="button">
                <img src="{%static './image/bin.png' %}" width="25vh" height="25vh">
            </button>
        </div>
        <div class="review-title">제목</div>
        <div class="review-content">후기 내용 후기 내용 후기 내용</div>
        <img width="100%" height="70%" src="https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMDEwMTRfMTg0%2FMDAxNjAyNjgzMTgxNTQ3.qcbTkNfzFY75fzTRZsyJo7OwWJVpx_uv3Lf1hXmlI6Eg.5VSSIqaB14PUuzKhlUAWB5fh5XfUkAcUSXbRnZv7nbog.JPEG.jeeyha%2FDSC04161.JPG" alt="이미지">
        <div class="review-under">
            <img src="{%static './image/star.png' %}">
            <div class="star-count">35</div>
            <img src="{%static './image/chat.png' %}">
            <div class="chat-count">2</div>
        </div>
        <hr clas="review-line" style="border: solid 2px #FFC700;">
        <div class="review-comment">
            <div class="review-comment-content">
                댓글을 남겨주세요.
            </div>
            <button class="review-send-button" type="button">
                <img src="{%static './image/review_send.png' %}">
            </button>
        </div>
    </div>
</body>
</html>

yeogiapp/templates/review_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="review">
        <img src="../image/user.png">
        <div class="user-info">
            <div>userID</div>
            <div>20XX.XX.XX</div>
        </div>
        <div>후기 내용 후기 내용</div>
    </div>
</body>
</html>